version: "3.8"

services:
  grigorishinfrontend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: grigorishinfrontend

  nginx-front:
    image: nginx:1.24.0
    container_name: nginx-front
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx-front.conf:/etc/nginx/nginx.conf
      - ./data/certbot-front/conf:/etc/letsencrypt:ro
      - ./data/certbot-front/www:/var/www/certbot:ro
    depends_on:
      - grigorishinfrontend

  certbot-front:
    image: certbot/certbot:latest
    container_name: certbot-front
    volumes:
      - ./data/certbot-front/conf:/etc/letsencrypt:rw
      - ./data/certbot-front/www:/var/www/certbot:rw
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email saifulinvladislav@gmail.com --agree-tos --no-eff-email -d grigorishin.net