version: "3.8"

services:
  grigorishinfrontend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: grigorishinfrontend
    volumes:
        - grigorishinfront-app:/app

  nginx-front:
    image: nginx:1.24.0
    container_name: nginx-front
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - grigorishinfront-app:/app
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/html
    depends_on:
      - grigorishinfrontend

  certbot-front:
    image: certbot/certbot:latest
    container_name: certbot-front
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/html
    depends_on:
      - nginx-front
    command: certonly --webroot --webroot-path=/var/www/html --email saifulinvladislav@gmail.com --agree-tos --no-eff-email -d grigorishin.net

volumes:
    certbot-etc:
    certbot-var:
    certbot-www:
    grigorishinfront-app: