version: "3.8"

services:
  grigorishinfrontend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: grigorishinfrontend
    volumes:
        - grigorishinfront-app:/app
    networks:
      - grigorishinfront
      - nginx

volumes:
    grigorishinfront-app:
      external: true

networks:
  grigorishinfront:
    external: true
  nginx:
    external: true
