version: "3.8"

services:
  grigorishinfrontend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: grigorishinfrontend
    volumes:
        - grigorishinfront-app:/app

volumes:
    grigorishinfront-app: