version: "3.8"

services:
  grigorishinfrontend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: grigorishinfrontend

  nginx-front:
    image: nginx:1.24.0
    container_name: nginx-front
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt-front:ro
      - ./data/certbot/www:/var/www/certbot-front:ro
    depends_on:
      - grigorishinfrontend

  certbot-front:
    image: certbot/certbot:latest
    container_name: certbot-front
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt-front:rw
      - ./data/certbot/www:/var/www/certbot-front:rw
    depends_on:
      - nginx-front
    command: certonly --webroot --webroot-path=/var/www/certbot-front --email saifulinvladislav@gmail.com --agree-tos --no-eff-email -d grigorishin.net